#include "pch.h"
#include "AliasBlockGenerator.h"

#include "AliasManager.h"





//
// Marker strings used to delimit the alias block in profile files.
// The scanner looks for these to find existing blocks.
//

static constexpr LPCWSTR k_pszHeaderMarker = L"#  TCDir Aliases";
static constexpr LPCWSTR k_pszFooterMarker = L"# End TCDir Aliases";





////////////////////////////////////////////////////////////////////////////////
//
//  CAliasBlockGenerator::Generate
//
//  Generates the complete PowerShell alias block from an SAliasConfig.
//  Output is a vector of lines (no trailing newlines on each line).
//
////////////////////////////////////////////////////////////////////////////////

void CAliasBlockGenerator::Generate (const SAliasConfig & config, const wstring & strVersion, vector<wstring> & rgBlockLines)
{
    rgBlockLines.clear();



    //
    // Header banner
    //

    rgBlockLines.push_back (L"################################################################################");
    rgBlockLines.push_back (L"#");
    rgBlockLines.push_back (format (L"#  TCDir Aliases -- Generated by tcdir v{}", strVersion));
    rgBlockLines.push_back (L"#");
    rgBlockLines.push_back (L"#  DO NOT EDIT: This block is managed by tcdir and will be replaced.");
    rgBlockLines.push_back (L"#  Run 'tcdir --set-aliases' to reconfigure, '--remove-aliases' to remove.");
    rgBlockLines.push_back (L"#");
    rgBlockLines.push_back (L"################################################################################");
    rgBlockLines.push_back (L"");

    //
    // Root alias function
    //

    wstring strInvocation = config.strTcDirInvocation;

    if (strInvocation.find (L' ') != wstring::npos)
    {
        // Path contains spaces — use call operator with quoting
        rgBlockLines.push_back (format (L"function {} {{ & \"{}\" @args }}", config.strRootAlias, strInvocation));
    }
    else
    {
        rgBlockLines.push_back (format (L"function {} {{ {} @args }}", config.strRootAlias, strInvocation));
    }

    //
    // Sub-alias functions
    //

    for (const auto & sub : config.rgSubAliases)
    {
        if (sub.fEnabled)
        {
            rgBlockLines.push_back (format (L"function {} {{ {} {} @args }}", sub.strName, config.strRootAlias, sub.strFlags));
        }
    }

    //
    // Footer banner
    //

    rgBlockLines.push_back (L"");
    rgBlockLines.push_back (L"################################################################################");
    rgBlockLines.push_back (L"# End TCDir Aliases");
    rgBlockLines.push_back (L"################################################################################");
}
