#include "pch.h"
#include "AliasBlockGenerator.h"

#include "AliasManager.h"





////////////////////////////////////////////////////////////////////////////////
//
//  CAliasBlockGenerator::Generate
//
//  Generates the complete PowerShell alias block from an SAliasConfig.
//  Output is a vector of lines (no trailing newlines on each line).
//
////////////////////////////////////////////////////////////////////////////////

void CAliasBlockGenerator::Generate (const SAliasConfig & config, const wstring & strVersion, vector<wstring> & rgBlockLines)
{
    rgBlockLines.clear();



    //
    // Header banner
    //

    rgBlockLines.push_back (L"################################################################################");
    rgBlockLines.push_back (L"#");
    rgBlockLines.push_back (format (L"#  TCDir Aliases -- Generated by tcdir v{}", strVersion));
    rgBlockLines.push_back (L"#");
    rgBlockLines.push_back (L"#  DO NOT EDIT: This block is managed by tcdir and will be replaced.");
    rgBlockLines.push_back (L"#  Run 'tcdir --set-aliases' to reconfigure, '--remove-aliases' to remove.");
    rgBlockLines.push_back (L"#");
    rgBlockLines.push_back (L"################################################################################");
    rgBlockLines.push_back (L"");

    //
    // Compute column widths for aligned output
    //

    wstring strInvocation = config.strTcDirInvocation;
    bool    fQuotePath    = (strInvocation.find (L' ') != wstring::npos);

    //
    // Build the body string for each function, then compute max widths
    //

    wstring              strRootBody = fQuotePath
                                     ? format (L"& \"{}\" @args", strInvocation)
                                     : format (L"{} @args", strInvocation);

    size_t               cchMaxName  = config.strRootAlias.size();
    size_t               cchMaxBody  = strRootBody.size();
    vector<wstring>      rgSubBodies;

    for (const auto & sub : config.rgSubAliases)
    {
        if (sub.fEnabled)
        {
            wstring body = format (L"{} {} @args", config.strRootAlias, QuotePsFlags (sub.strFlags));

            cchMaxName = max (cchMaxName, sub.strName.size());
            cchMaxBody = max (cchMaxBody, body.size());
            rgSubBodies.push_back (body);
        }
    }

    //
    // Root alias function
    //

    rgBlockLines.push_back (format (L"function {:<{}} {{ {:<{}} }}", config.strRootAlias, cchMaxName, strRootBody, cchMaxBody));

    //
    // Sub-alias functions
    //

    {
        size_t iBody = 0;

        for (const auto & sub : config.rgSubAliases)
        {
            if (sub.fEnabled)
            {
                rgBlockLines.push_back (format (L"function {:<{}} {{ {:<{}} }}", sub.strName, cchMaxName, rgSubBodies[iBody], cchMaxBody));
                ++iBody;
            }
        }
    }

    //
    // Footer banner
    //

    rgBlockLines.push_back (L"");
    rgBlockLines.push_back (L"################################################################################");
    rgBlockLines.push_back (L"#  End TCDir Aliases");
    rgBlockLines.push_back (L"################################################################################");
}





////////////////////////////////////////////////////////////////////////////////
//
//  CAliasBlockGenerator::QuotePsFlags
//
//  Quote individual flag tokens that would be misinterpreted by PowerShell.
//  PowerShell treats -name:value as named-parameter binding inside function
//  calls, which splits e.g. "-a:d" into two arguments.  Wrapping such tokens
//  in single quotes prevents the split.
//
//  Tokens that start with '-' and contain ':' are wrapped in single quotes.
//  Multi-token flags (e.g., "-s -b") are split, quoted individually if needed,
//  and reassembled.
//
////////////////////////////////////////////////////////////////////////////////

wstring CAliasBlockGenerator::QuotePsFlags (const wstring & strFlags)
{
    wstring strResult;
    wistringstream stream (strFlags);
    wstring strToken;
    bool fFirst = true;

    while (stream >> strToken)
    {
        if (!fFirst)
        {
            strResult += L' ';
        }
        fFirst = false;

        if (strToken.size() >= 2 && strToken[0] == L'-' && strToken.find (L':') != wstring::npos)
        {
            strResult += L'\'';
            strResult += strToken;
            strResult += L'\'';
        }
        else
        {
            strResult += strToken;
        }
    }

    return strResult;
}
