#include "pch.h"
#include "EhmTestHelper.h"
#include "../TCDirCore/ProfileFileManager.h"
#include "../TCDirCore/AliasBlockGenerator.h"
#include "../TCDirCore/AliasManager.h"





using namespace Microsoft::VisualStudio::CppUnitTestFramework;





namespace UnitTest
{
    TEST_CLASS(ProfileFileManagerTests)
    {
    public:

        TEST_CLASS_INITIALIZE(ClassInitialize)
        {
            SetupEhmForUnitTests();
        }




        TEST_METHOD(FindAliasBlock_NoBlock_ReturnsNotFound)
        {
            vector<wstring> rgLines = { L"# some content", L"Set-Location C:\\code" };

            CProfileFileManager fileMgr;
            SAliasBlock         block;

            HRESULT hr = fileMgr.FindAliasBlock (rgLines, block);



            Assert::IsTrue (SUCCEEDED (hr));
            Assert::IsFalse (block.fFound);
        }




        TEST_METHOD(FindAliasBlock_WithBlock_DetectsCorrectly)
        {
            vector<wstring> rgLines = {
                L"# other stuff",
                L"################################################################################",
                L"#",
                L"#  TCDir Aliases -- Generated by tcdir v5.2.1150",
                L"#",
                L"################################################################################",
                L"",
                L"function d { tcdir @args }",
                L"function dd { d /a:d @args }",
                L"",
                L"################################################################################",
                L"#  End TCDir Aliases",
                L"################################################################################",
                L"# more stuff",
            };

            CProfileFileManager fileMgr;
            SAliasBlock         block;

            HRESULT hr = fileMgr.FindAliasBlock (rgLines, block);



            Assert::IsTrue (SUCCEEDED (hr));
            Assert::IsTrue (block.fFound);
            Assert::AreEqual (1u, static_cast<unsigned>(block.iStartLine));
            Assert::AreEqual (12u, static_cast<unsigned>(block.iEndLine));
            Assert::AreEqual (L"d", block.strRootAlias.c_str());
            Assert::AreEqual (2u, static_cast<unsigned>(block.rgAliasNames.size()));
            Assert::AreEqual (L"5.2.1150", block.strVersion.c_str());
        }




        TEST_METHOD(ReplaceAliasBlock_ReplacesCorrectly)
        {
            vector<wstring> rgLines = {
                L"# before",
                L"OLD_LINE_1",
                L"OLD_LINE_2",
                L"OLD_LINE_3",
                L"# after",
            };

            SAliasBlock block;

            block.iStartLine = 1;
            block.iEndLine   = 3;
            block.fFound     = true;

            vector<wstring> rgNewBlock = { L"NEW_LINE_1", L"NEW_LINE_2" };

            CProfileFileManager fileMgr;



            fileMgr.ReplaceAliasBlock (rgLines, block, rgNewBlock);

            Assert::AreEqual (4u, static_cast<unsigned>(rgLines.size()));
            Assert::AreEqual (L"# before",   rgLines[0].c_str());
            Assert::AreEqual (L"NEW_LINE_1", rgLines[1].c_str());
            Assert::AreEqual (L"NEW_LINE_2", rgLines[2].c_str());
            Assert::AreEqual (L"# after",    rgLines[3].c_str());
        }




        TEST_METHOD(AppendAliasBlock_AppendsCorrectly)
        {
            vector<wstring> rgLines    = { L"existing content" };
            vector<wstring> rgNewBlock = { L"new block" };

            CProfileFileManager fileMgr;



            fileMgr.AppendAliasBlock (rgLines, rgNewBlock);

            Assert::AreEqual (3u, static_cast<unsigned>(rgLines.size()));
            Assert::AreEqual (L"existing content", rgLines[0].c_str());
            Assert::AreEqual (L"",                 rgLines[1].c_str());
            Assert::AreEqual (L"new block",        rgLines[2].c_str());
        }




        TEST_METHOD(RemoveAliasBlock_RemovesCorrectly)
        {
            vector<wstring> rgLines = {
                L"# before",
                L"BLOCK_1",
                L"BLOCK_2",
                L"# after",
            };

            SAliasBlock block;

            block.iStartLine = 1;
            block.iEndLine   = 2;
            block.fFound     = true;

            CProfileFileManager fileMgr;



            fileMgr.RemoveAliasBlock (rgLines, block);

            Assert::AreEqual (2u, static_cast<unsigned>(rgLines.size()));
            Assert::AreEqual (L"# before", rgLines[0].c_str());
            Assert::AreEqual (L"# after",  rgLines[1].c_str());
        }
    };
}
