#include "pch.h"
#include "EhmTestHelper.h"
#include "../TCDirCore/ProfileFileManager.h"
#include "../TCDirCore/AliasBlockGenerator.h"
#include "../TCDirCore/AliasManager.h"





using namespace Microsoft::VisualStudio::CppUnitTestFramework;





namespace UnitTest
{
    //
    // Helper to create a temp file with given content
    //

    static wstring CreateTempProfileFile (const wstring & strContent, bool fWriteBom = false)
    {
        WCHAR szTempDir[MAX_PATH]  = {};
        WCHAR szTempFile[MAX_PATH] = {};

        GetTempPathW (MAX_PATH, szTempDir);
        GetTempFileNameW (szTempDir, L"pf", 0, szTempFile);

        FILE * pf = nullptr;

        _wfopen_s (&pf, szTempFile, L"wb");

        if (pf != nullptr)
        {
            if (fWriteBom)
            {
                unsigned char bom[] = { 0xEF, 0xBB, 0xBF };
                fwrite (bom, 1, 3, pf);
            }

            // Convert to UTF-8
            int cb = WideCharToMultiByte (CP_UTF8, 0, strContent.data(), static_cast<int>(strContent.size()), nullptr, 0, nullptr, nullptr);
            string strUtf8 (static_cast<size_t>(cb), '\0');
            WideCharToMultiByte (CP_UTF8, 0, strContent.data(), static_cast<int>(strContent.size()), strUtf8.data(), cb, nullptr, nullptr);
            fwrite (strUtf8.data(), 1, strUtf8.size(), pf);

            fclose (pf);
        }

        return szTempFile;
    }





    TEST_CLASS(ProfileFileManagerTests)
    {
    public:

        TEST_CLASS_INITIALIZE(ClassInitialize)
        {
            SetupEhmForUnitTests();
        }




        TEST_METHOD(ReadProfileFile_BasicContent)
        {
            wstring strPath = CreateTempProfileFile (L"line1\r\nline2\r\nline3");

            CProfileFileManager fileMgr;
            vector<wstring>     rgLines;
            bool                fHasBom = false;

            HRESULT hr = fileMgr.ReadProfileFile (strPath, rgLines, fHasBom);



            Assert::IsTrue (SUCCEEDED (hr));
            Assert::AreEqual (3u, static_cast<unsigned>(rgLines.size()));
            Assert::AreEqual (L"line1", rgLines[0].c_str());
            Assert::AreEqual (L"line2", rgLines[1].c_str());
            Assert::AreEqual (L"line3", rgLines[2].c_str());
            Assert::IsFalse (fHasBom);

            DeleteFileW (strPath.c_str());
        }




        TEST_METHOD(ReadProfileFile_Utf8Bom_Preserved)
        {
            wstring strPath = CreateTempProfileFile (L"# profile content\r\n", true);

            CProfileFileManager fileMgr;
            vector<wstring>     rgLines;
            bool                fHasBom = false;

            HRESULT hr = fileMgr.ReadProfileFile (strPath, rgLines, fHasBom);



            Assert::IsTrue (SUCCEEDED (hr));
            Assert::IsTrue (fHasBom);

            DeleteFileW (strPath.c_str());
        }




        TEST_METHOD(FindAliasBlock_NoBlock_ReturnsNotFound)
        {
            vector<wstring> rgLines = { L"# some content", L"Set-Location C:\\code" };

            CProfileFileManager fileMgr;
            SAliasBlock         block;

            HRESULT hr = fileMgr.FindAliasBlock (rgLines, block);



            Assert::IsTrue (SUCCEEDED (hr));
            Assert::IsFalse (block.fFound);
        }




        TEST_METHOD(FindAliasBlock_WithBlock_DetectsCorrectly)
        {
            vector<wstring> rgLines = {
                L"# other stuff",
                L"################################################################################",
                L"#",
                L"#  TCDir Aliases -- Generated by tcdir v5.2.1150",
                L"#",
                L"################################################################################",
                L"",
                L"function d { tcdir @args }",
                L"function dd { d /a:d @args }",
                L"",
                L"################################################################################",
                L"# End TCDir Aliases",
                L"################################################################################",
                L"# more stuff",
            };

            CProfileFileManager fileMgr;
            SAliasBlock         block;

            HRESULT hr = fileMgr.FindAliasBlock (rgLines, block);



            Assert::IsTrue (SUCCEEDED (hr));
            Assert::IsTrue (block.fFound);
            Assert::AreEqual (1u, static_cast<unsigned>(block.iStartLine));
            Assert::AreEqual (12u, static_cast<unsigned>(block.iEndLine));
            Assert::AreEqual (L"d", block.strRootAlias.c_str());
            Assert::AreEqual (2u, static_cast<unsigned>(block.rgAliasNames.size()));
            Assert::AreEqual (L"5.2.1150", block.strVersion.c_str());
        }




        TEST_METHOD(WriteProfileFile_RoundTrip)
        {
            WCHAR szTempDir[MAX_PATH]  = {};
            WCHAR szTempFile[MAX_PATH] = {};

            GetTempPathW (MAX_PATH, szTempDir);
            GetTempFileNameW (szTempDir, L"pf", 0, szTempFile);

            CProfileFileManager fileMgr;
            vector<wstring>     rgLines = { L"line1", L"line2" };

            HRESULT hr = fileMgr.WriteProfileFile (szTempFile, rgLines, false);



            Assert::IsTrue (SUCCEEDED (hr));

            vector<wstring> rgReadBack;
            bool            fHasBom = false;

            hr = fileMgr.ReadProfileFile (szTempFile, rgReadBack, fHasBom);

            Assert::IsTrue (SUCCEEDED (hr));
            Assert::AreEqual (2u, static_cast<unsigned>(rgReadBack.size()));
            Assert::AreEqual (L"line1", rgReadBack[0].c_str());
            Assert::AreEqual (L"line2", rgReadBack[1].c_str());

            DeleteFileW (szTempFile);
        }




        TEST_METHOD(WriteProfileFile_PreservesBom)
        {
            WCHAR szTempDir[MAX_PATH]  = {};
            WCHAR szTempFile[MAX_PATH] = {};

            GetTempPathW (MAX_PATH, szTempDir);
            GetTempFileNameW (szTempDir, L"pf", 0, szTempFile);

            CProfileFileManager fileMgr;
            vector<wstring>     rgLines = { L"test" };



            fileMgr.WriteProfileFile (szTempFile, rgLines, true);

            // Re-read and verify BOM
            vector<wstring> rgReadBack;
            bool            fHasBom = false;

            fileMgr.ReadProfileFile (szTempFile, rgReadBack, fHasBom);

            Assert::IsTrue (fHasBom);

            DeleteFileW (szTempFile);
        }




        TEST_METHOD(CreateBackup_CreatesFile)
        {
            wstring strPath = CreateTempProfileFile (L"original content");

            CProfileFileManager fileMgr;

            fileMgr.CreateBackup (strPath);



            // Find the timestamped .bak file (e.g., filename.2026-03-26-05-37-10.bak)
            filesystem::path parentDir = filesystem::path (strPath).parent_path();
            wstring          strStem   = filesystem::path (strPath).filename().wstring();
            bool             fFoundBak = false;
            wstring          strBakPath;

            for (const auto & entry : filesystem::directory_iterator (parentDir))
            {
                wstring name = entry.path().filename().wstring();

                if (name.starts_with (strStem) && name.ends_with (L".bak"))
                {
                    fFoundBak  = true;
                    strBakPath = entry.path().wstring();
                    break;
                }
            }

            Assert::IsTrue (fFoundBak);

            DeleteFileW (strPath.c_str());
            DeleteFileW (strBakPath.c_str());
        }




        TEST_METHOD(ReplaceAliasBlock_ReplacesCorrectly)
        {
            vector<wstring> rgLines = {
                L"# before",
                L"OLD_LINE_1",
                L"OLD_LINE_2",
                L"OLD_LINE_3",
                L"# after",
            };

            SAliasBlock block;

            block.iStartLine = 1;
            block.iEndLine   = 3;
            block.fFound     = true;

            vector<wstring> rgNewBlock = { L"NEW_LINE_1", L"NEW_LINE_2" };

            CProfileFileManager fileMgr;



            fileMgr.ReplaceAliasBlock (rgLines, block, rgNewBlock);

            Assert::AreEqual (4u, static_cast<unsigned>(rgLines.size()));
            Assert::AreEqual (L"# before",   rgLines[0].c_str());
            Assert::AreEqual (L"NEW_LINE_1", rgLines[1].c_str());
            Assert::AreEqual (L"NEW_LINE_2", rgLines[2].c_str());
            Assert::AreEqual (L"# after",    rgLines[3].c_str());
        }




        TEST_METHOD(AppendAliasBlock_AppendsCorrectly)
        {
            vector<wstring> rgLines    = { L"existing content" };
            vector<wstring> rgNewBlock = { L"new block" };

            CProfileFileManager fileMgr;



            fileMgr.AppendAliasBlock (rgLines, rgNewBlock);

            Assert::AreEqual (3u, static_cast<unsigned>(rgLines.size()));
            Assert::AreEqual (L"existing content", rgLines[0].c_str());
            Assert::AreEqual (L"",                 rgLines[1].c_str());
            Assert::AreEqual (L"new block",        rgLines[2].c_str());
        }




        TEST_METHOD(RemoveAliasBlock_RemovesCorrectly)
        {
            vector<wstring> rgLines = {
                L"# before",
                L"BLOCK_1",
                L"BLOCK_2",
                L"# after",
            };

            SAliasBlock block;

            block.iStartLine = 1;
            block.iEndLine   = 2;
            block.fFound     = true;

            CProfileFileManager fileMgr;



            fileMgr.RemoveAliasBlock (rgLines, block);

            Assert::AreEqual (2u, static_cast<unsigned>(rgLines.size()));
            Assert::AreEqual (L"# before", rgLines[0].c_str());
            Assert::AreEqual (L"# after",  rgLines[1].c_str());
        }
    };
}
